export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAILURE = 'ORDER_LIST_FAILURE';

export const ORDER_REMOVE_REQUEST = 'ORDER_REMOVE_REQUEST';
export const ORDER_REMOVE_SUCCESS = 'ORDER_REMOVE_SUCCESS';
export const ORDER_REMOVE_FAILURE = 'ORDER_REMOVE_FAILURE';

export const GET_COMPANY_REQUEST = 'GET_COMPANY_REQUEST';
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS';
export const GET_COMPANY_FAILURE = 'GET_COMPANY_FAILURE';
