export const COMPANY_AND_PRODUCT_LIST_FAILURE = 'COMPANY_AND_PRODUCT_LIST_FAILURE';
export const COMPANY_AND_PRODUCT_LIST_REQUEST = 'COMPANY_AND_PRODUCT_LIST_REQUEST';
export const COMPANY_AND_PRODUCT_LIST_SUCCESS = 'COMPANY_AND_PRODUCT_LIST_SUCCESS';

export const ORDER_CREATE_FAILURE = 'ORDER_CREATE_FAILURE';
export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';

export const ADD_PRODUCT_TO_ORDER = 'ADD_PRODUCT_TO_ORDER';
export const REMOVE_PRODUCT_FROM_ORDER = 'REMOVE_PRODUCT_FROM_ORDER';
export const RESET_ORDER = 'RESET_ORDER';
export const CHANGE_COMPANY_IN_ORDER = 'CHANGE_COMPANY_IN_ORDER';
export const SHOW_COMPANY_REQUIRED = 'SHOW_COMPANY_REQUIRED';
export const HIDE_COMPANY_REQUIRED = 'HIDE_COMPANY_REQUIRED';
