export const ACCOUNT_CREATION_FAILURE = 'ACCOUNT_CREATION_FAILURE';
export const ACCOUNT_CREATION_REQUEST = 'ACCOUNT_CREATION_REQUEST';
export const ACCOUNT_CREATION_SUCCESS = 'ACCOUNT_CREATION_SUCCESS';
